### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by PeerHerholz** [timsainb/science_vector_images#1]
Ahoi hoi @timsainb,

thank you very much for sharing this, love the looks!
While I was going through the materials, I notices that
the repo so far doesn't have any license. Hence, reusability
might suffer as folks would always have to ask you before 
using the graphics. Sorry, I don't mean to overstep here, I just
thought it'll ease up everyones' life, hehe. Just in case you want to
add one and you're not sure which, here's a nice starting point:
https://choosealicense.com/. 
Would be great to hear your thought on this.

Thanks again!

Best, Peer

**Comment by timsainb** [comment]
Good point, I added one!

**Comment by PeerHerholz** [comment]
Cool, thanks a lot!
